# Generated by Django 3.2.5 on 2021-10-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_pricing',
            field=models.BooleanField(default=False),
        ),
    ]
