# Generated by Django 3.2.5 on 2021-07-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210728_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ap_email',
            field=models.EmailField(default='test@test.com', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='main_email',
            field=models.EmailField(default='test@test.com', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='street_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
