# Generated by Django 3.2.5 on 2021-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_user_requestedcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ap_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='main_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='employeeType',
            field=models.CharField(choices=[(1, 'EMT'), (2, 'Paramedic'), (3, 'RN'), (4, 'Admin'), (5, 'SuperUser'), (6, 'Accounting')], default=1, max_length=20),
        ),
    ]
