# Generated by Django 3.2.5 on 2021-07-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210729_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documentName',
            new_name='document_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documentType',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employeeType',
            new_name='employee_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='requestedCompany',
            new_name='requested_company',
        ),
    ]
