# Generated by Django 3.2.5 on 2021-08-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210729_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[(1, 'Medicine'), (2, 'Procedure'), (3, 'Protocol')], max_length=20)),
                ('document_detail_name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_headers', to='company.company')),
            ],
            options={
                'ordering': ['document_detail_name'],
            },
        ),
    ]
