# Generated by Django 3.2.5 on 2021-08-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_documentheader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentheader',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='documentheader',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
