# Generated by Django 3.2.5 on 2021-08-12 14:42

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210803_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='table_data',
            field=models.JSONField(default=company.models.Document.table_default),
        ),
    ]
