# Generated by Django 3.2.5 on 2021-08-20 12:55

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_document_table_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='flow_data',
            field=models.JSONField(default=company.models.Document.flow_default),
        ),
    ]
