# Generated by Django 3.2.5 on 2021-09-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20210906_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentimage',
            name='company',
        ),
    ]
