# Generated by Django 3.2.5 on 2021-09-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_remove_documentimage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimage',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_images', to='company.company'),
        ),
    ]
