# Generated by Django 3.2.5 on 2021-09-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_documentimage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_cus_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
