# Generated by Django 3.2.5 on 2021-09-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_subsciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='subsciption',
            new_name='subscription',
        ),
    ]
