# Generated by Django 3.2.5 on 2021-09-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('company', '0017_rename_subsciption_company_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='payments.subscription'),
        ),
    ]
