# Generated by Django 3.2.5 on 2021-09-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_company_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='company.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requested_users', to='company.company'),
        ),
    ]
