# Generated by Django 3.2.5 on 2021-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20210914_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_sub_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
